# Generated by Django 3.2.18 on 2023-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseballsTest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_id', models.PositiveIntegerField()),
                ('player_name', models.CharField(max_length=200)),
                ('player_birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'baseballs_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BattingInfo',
            fields=[
                ('yyyymmdd', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=10)),
                ('player_birth', models.DateField()),
                ('team', models.CharField(max_length=10)),
                ('p', models.CharField(db_column='P', max_length=10)),
                ('tpa', models.IntegerField(blank=True, db_column='TPA', null=True)),
                ('ab', models.IntegerField(blank=True, db_column='AB', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('go', models.IntegerField(blank=True, db_column='GO', null=True)),
                ('fo', models.IntegerField(blank=True, db_column='FO', null=True)),
                ('pit', models.IntegerField(blank=True, db_column='PIT', null=True)),
                ('gdp', models.IntegerField(blank=True, db_column='GDP', null=True)),
                ('lob', models.IntegerField(blank=True, db_column='LOB', null=True)),
                ('avg', models.DecimalField(blank=True, db_column='AVG', decimal_places=3, max_digits=5, null=True)),
                ('ops', models.DecimalField(blank=True, db_column='OPS', decimal_places=3, max_digits=5, null=True)),
                ('li', models.DecimalField(blank=True, db_column='LI', decimal_places=2, max_digits=5, null=True)),
                ('wpa', models.DecimalField(blank=True, db_column='WPA', decimal_places=3, max_digits=5, null=True)),
                ('re24', models.DecimalField(blank=True, db_column='RE24', decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'batting_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PitchingInfo',
            fields=[
                ('yyyymmdd', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=10)),
                ('player_birth', models.DateField()),
                ('team', models.CharField(max_length=10)),
                ('today_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ip', models.FloatField(blank=True, db_column='IP', null=True)),
                ('tbf', models.IntegerField(blank=True, db_column='TBF', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('k', models.IntegerField(blank=True, db_column='K', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('go_fo', models.CharField(blank=True, db_column='GO-FO', max_length=10, null=True)),
                ('pit_s', models.CharField(blank=True, db_column='PIT-S', max_length=10, null=True)),
                ('ir_is', models.CharField(blank=True, db_column='IR-IS', max_length=10, null=True)),
                ('gsc', models.IntegerField(blank=True, db_column='GSC', null=True)),
                ('era', models.DecimalField(blank=True, db_column='ERA', decimal_places=2, max_digits=5, null=True)),
                ('whip', models.CharField(blank=True, db_column='WHIP', max_length=10, null=True)),
                ('li', models.DecimalField(blank=True, db_column='LI', decimal_places=2, max_digits=5, null=True)),
                ('wpa', models.DecimalField(blank=True, db_column='WPA', decimal_places=3, max_digits=5, null=True)),
                ('re24', models.DecimalField(blank=True, db_column='RE24', decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'pitching_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=10)),
                ('player_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyBattingInfo',
            fields=[
                ('week', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=10)),
                ('player_birth', models.DateField()),
                ('team', models.CharField(max_length=10)),
                ('tpa', models.IntegerField(blank=True, db_column='TPA', null=True)),
                ('rtpa', models.FloatField(blank=True, db_column='RTPA', null=True)),
                ('ab', models.IntegerField(blank=True, db_column='AB', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('rbi', models.IntegerField(blank=True, db_column='RBI', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('so', models.IntegerField(blank=True, db_column='SO', null=True)),
                ('go', models.IntegerField(blank=True, db_column='GO', null=True)),
                ('fo', models.IntegerField(blank=True, db_column='FO', null=True)),
                ('pit', models.IntegerField(blank=True, db_column='PIT', null=True)),
                ('gdp', models.IntegerField(blank=True, db_column='GDP', null=True)),
                ('lob', models.IntegerField(blank=True, db_column='LOB', null=True)),
                ('avg', models.DecimalField(blank=True, db_column='AVG', decimal_places=3, max_digits=5, null=True)),
                ('game_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_batting_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyPitchingInfo',
            fields=[
                ('week', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=10)),
                ('player_birth', models.DateField()),
                ('team', models.CharField(max_length=10)),
                ('today_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ip', models.FloatField(blank=True, db_column='IP', null=True)),
                ('rip', models.FloatField(blank=True, db_column='RIP', null=True)),
                ('tbf', models.IntegerField(blank=True, db_column='TBF', null=True)),
                ('h', models.IntegerField(blank=True, db_column='H', null=True)),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('er', models.IntegerField(blank=True, db_column='ER', null=True)),
                ('bb', models.IntegerField(blank=True, db_column='BB', null=True)),
                ('hbp', models.IntegerField(blank=True, db_column='HBP', null=True)),
                ('k', models.IntegerField(blank=True, db_column='K', null=True)),
                ('hr', models.IntegerField(blank=True, db_column='HR', null=True)),
                ('game_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_pitching_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
